import {useMemo,useState} from 'react';
import {useDashboard} from '../hooks/useDashboard';
import {CashChart} from '../components/CashChart';
import {StatCard} from '../components/StatCard';
import {StatusPanel} from '../components/StatusPanel';
const money=(v:number,c:string)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c}).format(v/100);
export function DashboardPage(){
 const[now]=useState(()=>Math.floor(Date.now()/1000));const[days,setDays]=useState(30);const[horizon,setHorizon]=useState(14);const currency='INR';const[key,setKey]=useState(()=>sessionStorage.getItem('finctrl_api_key')||'');
 const{data,loading,error,authStatus,refresh}=useDashboard(key,now-days*86400,now,horizon,currency);const cash=data?.forecast.currencies[currency];const pending=useMemo(()=>data?.investigations.filter(i=>i.approval?.status==='PENDING').length||0,[data]);const latest=data?.runs[0];
 const saveKey=(v:string)=>{setKey(v);if(v)sessionStorage.setItem('finctrl_api_key',v);else sessionStorage.removeItem('finctrl_api_key')};
 return <><header><div><p className="eyebrow">Finance operations</p><h1>FINCTRL Control Room</h1></div><nav aria-label="Dashboard controls"><label>Window<select value={days} onChange={e=>setDays(+e.target.value)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><label>Forecast<select value={horizon} onChange={e=>setHorizon(+e.target.value)}><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><label>Currency<select value={currency} disabled><option>INR</option></select></label><button onClick={()=>void refresh()} disabled={loading}>Refresh</button></nav></header><main>
 <section className="credential"><label>Backend API key<input aria-label="Backend API key" type="password" value={key} onChange={e=>saveKey(e.target.value)}/></label><button type="button" onClick={()=>saveKey('')} disabled={!key}>Clear authentication</button><span>Stored only for this browser session.</span></section>
 {loading&&<div className="state" role="status">Loading authoritative financial data…</div>}{error&&<div className="state error" role="alert">{authStatus===401?'Authentication required':authStatus===403?'Access forbidden':error}</div>}
 {data&&cash&&<><section className="stats"><StatCard label="Net cash movement" value={money(cash.totals.historical_net,currency)}/><StatCard label="Forecast net" value={cash.forecast_available?money(cash.totals.forecast_net,currency):'Unavailable'}/><StatCard label="Open exceptions" value={String(data.exceptions.filter(e=>['OPEN','INVESTIGATING'].includes(e.status)).length)}/><StatCard label="Pending AI approvals" value={String(pending)}/><StatCard label="Latest reconciliation" value={latest?.status||'No runs'}/></section>
 <section className="grid wide"><StatusPanel title="Cash history + forecast">{cash.forecast_available?<CashChart series={cash}/>:<div className="empty">Forecast unavailable: {cash.unavailable_reason}</div>}<p className="method">{data.forecast.methodology}</p><small>{data.forecast.source.record_count} bank records · {data.forecast.source.currency_assumption}</small></StatusPanel><StatusPanel title="Reconciliation health">{latest?<dl><dt>Status</dt><dd>{latest.status}</dd><dt>Matches</dt><dd>{latest.matches_created}</dd><dt>Candidates</dt><dd>{latest.candidates_created}</dd><dt>Exceptions</dt><dd>{latest.exceptions_created}</dd></dl>:<div className="empty">No reconciliation runs.</div>}</StatusPanel></section>
 <section className="grid"><StatusPanel title="Exception severity"><ul>{['CRITICAL','HIGH','MEDIUM','LOW'].map(level=><li key={level}><span>{level}</span><strong>{data.exceptions.filter(e=>e.severity===level&&e.status!=='RESOLVED').length}</strong></li>)}</ul></StatusPanel><StatusPanel title="AI investigation decisions"><ul><li><span>Pending approval</span><strong>{pending}</strong></li><li><span>Approved</span><strong>{data.investigations.filter(i=>i.approval?.status==='APPROVED').length}</strong></li><li><span>Rejected</span><strong>{data.investigations.filter(i=>i.approval?.status==='REJECTED').length}</strong></li></ul></StatusPanel><StatusPanel title="Razorpay synchronization">{data.sync.length?<ul>{data.sync.map(s=><li key={s.resource_type}><span>{s.resource_type}</span><strong>{s.status}</strong><small>{s.records_fetched??'—'} fetched · {s.last_run_at?new Date(s.last_run_at).toLocaleString():'Never'}</small></li>)}</ul>:<div className="empty">No synchronization state.</div>}</StatusPanel></section>
 <StatusPanel title="Recent critical exceptions">{data.exceptions.filter(e=>['CRITICAL','HIGH'].includes(e.severity)).length?<ul>{data.exceptions.filter(e=>['CRITICAL','HIGH'].includes(e.severity)).slice(0,5).map(e=><li key={e.id}><span><b>{e.severity}</b> {e.exception_type}</span><small>{e.description}</small></li>)}</ul>:<div className="empty">No critical or high exceptions.</div>}</StatusPanel></>}
 </main></>;
}
