import {fireEvent,render,screen,waitFor} from '@testing-library/react';import {beforeEach,describe,expect,it,vi} from 'vitest';import {DashboardPage} from '../pages/DashboardPage';import * as api from '../api/client';
vi.mock('../api/client',async()=>{const actual=await vi.importActual('../api/client');return{...actual,loadDashboard:vi.fn()}});
const load=vi.mocked(api.loadDashboard);
const data={forecast:{generated_at:'2026-08-30T00:00:00Z',from_ts:1,to_ts:2,horizon_days:14,method:'daily_mean_net_cash_v1',methodology:'Integer daily mean.',source:{record_count:2,calendar_days:2,populated_days:2,currency_assumption:'INR bank contract'},currencies:{INR:{historical:[{date:'2026-08-29',inflow:1000,outflow:200,net:800}],forecast:[{date:'2026-08-30',net:400}],totals:{historical_inflow:1000,historical_outflow:200,historical_net:800,forecast_net:400},forecast_available:true,unavailable_reason:null}}},metrics:{records_reconciled:1,candidates_created:1,open_exceptions_by_severity:{}},exceptions:[{id:'e1',exception_key:'x',exception_type:'MISSING_BANK',status:'OPEN',severity:'CRITICAL',description:'Critical bank evidence missing',created_at:'2026-08-30'}],investigations:[{status:'COMPLETED',approval:{status:'PENDING'},created_at:'2026-08-30'}],runs:[{id:'r1',status:'SUCCEEDED',requested_at:'x',completed_at:'x',matches_created:4,candidates_created:1,exceptions_created:1}],sync:[{resource_type:'payments',status:'SUCCEEDED',last_provider_timestamp:1,last_run_at:'2026-08-30',records_fetched:12}]};
beforeEach(()=>{sessionStorage.setItem('finctrl_api_key','read-key');load.mockReset()});
describe('dashboard',()=>{
 it('renders loading then operational data with actual and forecast distinction',async()=>{let resolve!:(v:any)=>void;load.mockReturnValue(new Promise(r=>{resolve=r}));render(<DashboardPage/>);expect(screen.getByRole('status')).toHaveTextContent('Loading');resolve(data);expect(await screen.findByText('Net cash movement')).toBeInTheDocument();expect(screen.getByText('● Actual')).toBeInTheDocument();expect(screen.getByText('◆ Forecast')).toBeInTheDocument();expect(screen.getByText('INR')).toBeInTheDocument()});
 it('shows critical exceptions, pending approval, reconciliation and sync health',async()=>{load.mockResolvedValue(data as any);render(<DashboardPage/>);expect(await screen.findByText('Critical bank evidence missing')).toBeInTheDocument();expect(screen.getByText('Pending AI approvals').nextSibling).toHaveTextContent('1');expect(screen.getAllByText('SUCCEEDED').length).toBeGreaterThan(0);expect(screen.getByText(/12 fetched/)).toBeInTheDocument()});
 it('renders failure, forbidden and neutral no-data states',async()=>{load.mockRejectedValueOnce(new api.ApiError(403,'no'));const view=render(<DashboardPage/>);expect(await screen.findByText('Access forbidden')).toBeInTheDocument();view.unmount();load.mockResolvedValue({...data,forecast:{...data.forecast,currencies:{INR:{...data.forecast.currencies.INR,historical:[],forecast:[],forecast_available:false,unavailable_reason:'No authoritative cash movements'}}},exceptions:[],investigations:[],runs:[],sync:[]} as any);render(<DashboardPage/>);expect(await screen.findByText('No bank activity in this window')).toBeInTheDocument();expect(screen.getByText('Forecast will appear when authoritative bank movements are available.')).toBeInTheDocument();expect(screen.getByText('Forecast net').parentElement).toHaveTextContent('—Awaiting bank activity');expect(screen.queryByText(/Forecast unavailable/)).not.toBeInTheDocument();const summary=screen.getByText('Forecast methodology');const disclosure=summary.closest('details');const methodology=screen.getByText('Integer daily mean.');expect(disclosure).not.toHaveAttribute('open');expect(methodology).not.toBeVisible();fireEvent.click(summary);expect(disclosure).toHaveAttribute('open');expect(methodology).toBeVisible();expect(screen.getByText('No reconciliation runs.')).toBeInTheDocument();expect(screen.getByText('No synchronization state.')).toBeInTheDocument()});
 it('refreshes data on demand',async()=>{load.mockResolvedValue(data as any);render(<DashboardPage/>);await screen.findByText('Net cash movement');fireEvent.click(screen.getByRole('button',{name:'Refresh'}));await waitFor(()=>expect(load).toHaveBeenCalledTimes(2))});
 it('distinguishes missing authentication from a general API failure',async()=>{sessionStorage.clear();const first=render(<DashboardPage/>);expect(await screen.findByText('Authentication required')).toBeInTheDocument();expect(load).not.toHaveBeenCalled();first.unmount();sessionStorage.setItem('finctrl_api_key','read-key');load.mockRejectedValue(new Error('Forecast service unavailable'));render(<DashboardPage/>);expect(await screen.findByText('Forecast service unavailable')).toBeInTheDocument()});
 it('removes the session credential when authentication is cleared',async()=>{load.mockResolvedValue(data as any);render(<DashboardPage/>);await screen.findByText('Net cash movement');fireEvent.click(screen.getByRole('button',{name:'Clear authentication'}));expect(sessionStorage.getItem('finctrl_api_key')).toBeNull();expect(screen.getByLabelText('Backend API key')).toHaveValue('')});
});
