"""Initial migration

Revision ID: c07ed3e51636
Revises:
Create Date: 2026-08-28 16:25:16.387587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07ed3e51636'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', database.models.UUIDType(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exceptions',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', database.models.UUIDType(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_events',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uix_provider_event_id')
    )
    op.create_index(op.f('ix_financial_events_provider'), 'financial_events', ['provider'], unique=False)
    op.create_index(op.f('ix_financial_events_provider_event_id'), 'financial_events', ['provider_event_id'], unique=False)
    op.create_table('reconciliation_candidates',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('candidate_type', sa.String(), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_matches',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_records',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('source_event_id', database.models.UUIDType(), nullable=True),
    sa.Column('transaction_ref', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_records_transaction_ref'), 'bank_records', ['transaction_ref'], unique=False)
    op.create_table('erp_records',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('source_event_id', database.models.UUIDType(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_records_reference_id'), 'erp_records', ['reference_id'], unique=False)
    op.create_table('match_evidence',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('match_id', database.models.UUIDType(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', database.models.UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['reconciliation_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('razorpay_orders',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('source_event_id', database.models.UUIDType(), nullable=True),
    sa.Column('rzp_order_id', sa.String(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at_ts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_orders_receipt'), 'razorpay_orders', ['receipt'], unique=False)
    op.create_index(op.f('ix_razorpay_orders_rzp_order_id'), 'razorpay_orders', ['rzp_order_id'], unique=False)
    op.create_table('razorpay_payments',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('source_event_id', database.models.UUIDType(), nullable=True),
    sa.Column('rzp_payment_id', sa.String(), nullable=False),
    sa.Column('rzp_order_id', sa.String(), nullable=True),
    sa.Column('rzp_settlement_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('amount_refunded', sa.Integer(), nullable=False),
    sa.Column('refund_status', sa.String(), nullable=True),
    sa.Column('captured', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_description', sa.String(), nullable=True),
    sa.Column('created_at_ts', sa.Integer(), nullable=False),
    sa.Column('reconciliation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_payments_rzp_order_id'), 'razorpay_payments', ['rzp_order_id'], unique=False)
    op.create_index(op.f('ix_razorpay_payments_rzp_payment_id'), 'razorpay_payments', ['rzp_payment_id'], unique=False)
    op.create_index(op.f('ix_razorpay_payments_rzp_settlement_id'), 'razorpay_payments', ['rzp_settlement_id'], unique=False)
    op.create_table('razorpay_refunds',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('source_event_id', database.models.UUIDType(), nullable=True),
    sa.Column('rzp_refund_id', sa.String(), nullable=False),
    sa.Column('rzp_payment_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('created_at_ts', sa.Integer(), nullable=False),
    sa.Column('reconciliation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_refunds_rzp_payment_id'), 'razorpay_refunds', ['rzp_payment_id'], unique=False)
    op.create_index(op.f('ix_razorpay_refunds_rzp_refund_id'), 'razorpay_refunds', ['rzp_refund_id'], unique=False)
    op.create_table('razorpay_settlements',
    sa.Column('id', database.models.UUIDType(), nullable=False),
    sa.Column('source_event_id', database.models.UUIDType(), nullable=True),
    sa.Column('rzp_settlement_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fees', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('utr', sa.String(), nullable=True),
    sa.Column('created_at_ts', sa.Integer(), nullable=False),
    sa.Column('reconciliation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_settlements_rzp_settlement_id'), 'razorpay_settlements', ['rzp_settlement_id'], unique=False)
    op.create_index(op.f('ix_razorpay_settlements_utr'), 'razorpay_settlements', ['utr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_razorpay_settlements_utr'), table_name='razorpay_settlements')
    op.drop_index(op.f('ix_razorpay_settlements_rzp_settlement_id'), table_name='razorpay_settlements')
    op.drop_table('razorpay_settlements')
    op.drop_index(op.f('ix_razorpay_refunds_rzp_refund_id'), table_name='razorpay_refunds')
    op.drop_index(op.f('ix_razorpay_refunds_rzp_payment_id'), table_name='razorpay_refunds')
    op.drop_table('razorpay_refunds')
    op.drop_index(op.f('ix_razorpay_payments_rzp_settlement_id'), table_name='razorpay_payments')
    op.drop_index(op.f('ix_razorpay_payments_rzp_payment_id'), table_name='razorpay_payments')
    op.drop_index(op.f('ix_razorpay_payments_rzp_order_id'), table_name='razorpay_payments')
    op.drop_table('razorpay_payments')
    op.drop_index(op.f('ix_razorpay_orders_rzp_order_id'), table_name='razorpay_orders')
    op.drop_index(op.f('ix_razorpay_orders_receipt'), table_name='razorpay_orders')
    op.drop_table('razorpay_orders')
    op.drop_table('match_evidence')
    op.drop_index(op.f('ix_erp_records_reference_id'), table_name='erp_records')
    op.drop_table('erp_records')
    op.drop_index(op.f('ix_bank_records_transaction_ref'), table_name='bank_records')
    op.drop_table('bank_records')
    op.drop_table('reconciliation_matches')
    op.drop_table('reconciliation_candidates')
    op.drop_index(op.f('ix_financial_events_provider_event_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_provider'), table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_table('exceptions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
